import { Metadata } from 'next';
import { SITE_CONFIG } from './constants';

interface GenerateMetadataProps {
  title?: string;
  description?: string;
  image?: string;
  noIndex?: boolean;
  path?: string;
  keywords?: string[];
}

// Location-specific keywords for local SEO
const LOCATION_KEYWORDS = [
  'Home loan',
  'Home loan in Indore',
  'Home loan in Burhanpur',
  'Home loan in Khandwa',
  'Home loan in Bhopal',
  'Home loan in Dehradun',
  'Home loan in Noida',
  'Home loan in Ghaziabad',
  'Home loan in Delhi',
  'Home loan in Raver',
  'Home loan in Pune',
  'Home loan in Bangalore',
  'Home loan DSA',
  'DSA',
  'Indore',
  'Khandwa',
  'Burhanpur',
  'Bhopal',
  'Dehradun',
  'Noida',
  'Ghaziabad',
  'Delhi',
  'Raver',
  'Pune',
  'Bangalore',
  'Home loan Indore',
  'Home loan Burhanpur',
  'Home loan Khandwa',
  'Home loan Bhopal',
  'Home loan Dehradun',
  'Home loan Noida',
  'Home loan Ghaziabad',
  'Home loan Delhi',
  'Home loan Raver',
  'Home loan Pune',
  'Home loan Bangalore',
  'DSA Indore',
  'DSA Burhanpur',
  'DSA Khandwa',
  'DSA Bhopal',
  'DSA Dehradun',
  'DSA Noida',
  'DSA Ghaziabad',
  'DSA Delhi',
  'DSA Raver',
  'DSA Pune',
  'DSA Bangalore',
  'Loan DSA',
  'Home loan agent',
  'Home loan broker',
  'Best home loan Indore',
  'Best home loan Burhanpur',
  'Best home loan Khandwa',
  'Best home loan Bhopal',
  'Best home loan Dehradun',
  'Best home loan Noida',
  'Best home loan Ghaziabad',
  'Best home loan Delhi',
  'Best home loan Raver',
  'Best home loan Pune',
  'Best home loan Bangalore',
  'Personal loan Bhopal',
  'Personal loan Dehradun',
  'Personal loan Noida',
  'Personal loan Ghaziabad',
  'Personal loan Delhi',
  'Personal loan Raver',
  'Personal loan Pune',
  'Personal loan Bangalore',
  'Business loan Bhopal',
  'Business loan Dehradun',
  'Business loan Noida',
  'Business loan Ghaziabad',
  'Business loan Delhi',
  'Business loan Raver',
  'Business loan Pune',
  'Business loan Bangalore',
  'Loan against property Bhopal',
  'Loan against property Dehradun',
  'Loan against property Noida',
  'Loan against property Ghaziabad',
  'Loan against property Delhi',
  'Loan against property Raver',
  'Loan against property Pune',
  'Loan against property Bangalore',
  'Mortgage loan Indore',
  'Mortgage loan Burhanpur',
  'Mortgage loan Khandwa',
  'Mortgage loan Bhopal',
  'Mortgage loan Dehradun',
  'Mortgage loan Noida',
  'Mortgage loan Ghaziabad',
  'Mortgage loan Delhi',
  'Mortgage loan Raver',
  'Mortgage loan Pune',
  'Mortgage loan Bangalore',
  'Mortgage loan in Indore',
  'Mortgage loan in Burhanpur',
  'Mortgage loan in Khandwa',
  'Mortgage loan in Bhopal',
  'Mortgage loan in Dehradun',
  'Mortgage loan in Noida',
  'Mortgage loan in Ghaziabad',
  'Mortgage loan in Delhi',
  'Mortgage loan in Raver',
  'Mortgage loan in Pune',
  'Mortgage loan in Bangalore',
  'Best mortgage loan Indore',
  'Best mortgage loan Burhanpur',
  'Best mortgage loan Khandwa',
  'Best mortgage loan Bhopal',
  'Best mortgage loan Dehradun',
  'Best mortgage loan Noida',
  'Best mortgage loan Ghaziabad',
  'Best mortgage loan Delhi',
  'Best mortgage loan Raver',
  'Best mortgage loan Pune',
  'Best mortgage loan Bangalore',
  'House purchase loan Indore',
  'House purchase loan Burhanpur',
  'House purchase loan Khandwa',
  'House purchase loan Bhopal',
  'House purchase loan Dehradun',
  'House purchase loan Noida',
  'House purchase loan Ghaziabad',
  'House purchase loan Delhi',
  'House purchase loan Raver',
  'House purchase loan Pune',
  'House purchase loan Bangalore',
  'Flat purchase loan Indore',
  'Flat purchase loan Burhanpur',
  'Flat purchase loan Khandwa',
  'Flat purchase loan Bhopal',
  'Flat purchase loan Dehradun',
  'Flat purchase loan Noida',
  'Flat purchase loan Ghaziabad',
  'Flat purchase loan Delhi',
  'Flat purchase loan Raver',
  'Flat purchase loan Pune',
  'Flat purchase loan Bangalore',
  'House construction loan Indore',
  'House construction loan Burhanpur',
  'House construction loan Khandwa',
  'House construction loan Bhopal',
  'House construction loan Dehradun',
  'House construction loan Noida',
  'House construction loan Ghaziabad',
  'House construction loan Delhi',
  'House construction loan Raver',
  'House construction loan Pune',
  'House construction loan Bangalore',
  'Plot purchase loan Indore',
  'Plot purchase loan Burhanpur',
  'Plot purchase loan Khandwa',
  'Plot purchase loan Bhopal',
  'Plot purchase loan Dehradun',
  'Plot purchase loan Noida',
  'Plot purchase loan Ghaziabad',
  'Plot purchase loan Delhi',
  'Plot purchase loan Raver',
  'Plot purchase loan Pune',
  'Plot purchase loan Bangalore',
  'Plot construction loan Indore',
  'Plot construction loan Burhanpur',
  'Plot construction loan Khandwa',
  'Plot construction loan Bhopal',
  'Plot construction loan Dehradun',
  'Plot construction loan Noida',
  'Plot construction loan Ghaziabad',
  'Plot construction loan Delhi',
  'Plot construction loan Raver',
  'Plot construction loan Pune',
  'Plot construction loan Bangalore',
  'Home loan takeover Indore',
  'Home loan takeover Burhanpur',
  'Home loan takeover Khandwa',
  'Home loan takeover Bhopal',
  'Home loan takeover Dehradun',
  'Home loan takeover Noida',
  'Home loan takeover Ghaziabad',
  'Home loan takeover Delhi',
  'Home loan takeover Raver',
  'Home loan takeover Pune',
  'Home loan takeover Bangalore',
  'Mortgage loan takeover Indore',
  'Mortgage loan takeover Burhanpur',
  'Mortgage loan takeover Khandwa',
  'Mortgage loan takeover Bhopal',
  'Mortgage loan takeover Dehradun',
  'Mortgage loan takeover Noida',
  'Mortgage loan takeover Ghaziabad',
  'Mortgage loan takeover Delhi',
  'Mortgage loan takeover Raver',
  'Mortgage loan takeover Pune',
  'Mortgage loan takeover Bangalore',
  'Balance transfer Indore',
  'Balance transfer Burhanpur',
  'Balance transfer Khandwa',
  'Balance transfer Bhopal',
  'Balance transfer Dehradun',
  'Balance transfer Noida',
  'Balance transfer Ghaziabad',
  'Balance transfer Delhi',
  'Balance transfer Raver',
  'Balance transfer Pune',
  'Balance transfer Bangalore',
  'Top up loan Indore',
  'Top up loan Burhanpur',
  'Top up loan Khandwa',
  'Top up loan Bhopal',
  'Top up loan Dehradun',
  'Top up loan Noida',
  'Top up loan Ghaziabad',
  'Top up loan Delhi',
  'Top up loan Raver',
  'Top up loan Pune',
  'Top up loan Bangalore',
];

/**
 * Generate SEO-optimized metadata for pages with location-specific keywords
 */
export function generateMetadata({
  title,
  description,
  image,
  noIndex = false,
  path = '',
  keywords = [],
}: GenerateMetadataProps): Metadata {
  const pageTitle = title
    ? `${title} | ${SITE_CONFIG.name}`
    : SITE_CONFIG.name;
  const pageDescription = description || SITE_CONFIG.description;
  const pageImage = image || SITE_CONFIG.ogImage;
  const pageUrl = `${SITE_CONFIG.url}${path}`;
  
  // Combine custom keywords with location keywords
  const allKeywords = [
    ...keywords,
    ...LOCATION_KEYWORDS,
    'Home Loan',
    'Mortgage Loan',
    'Balance Transfer',
    'Top-Up Loan',
    'LAP',
    'Loan Against Property',
  ].join(', ');

  return {
    title: pageTitle,
    description: pageDescription,
    keywords: allKeywords,
    metadataBase: new URL(SITE_CONFIG.url),
    alternates: {
      canonical: pageUrl,
    },
    openGraph: {
      title: pageTitle,
      description: pageDescription,
      url: pageUrl,
      siteName: SITE_CONFIG.name,
      images: [
        {
          url: pageImage,
          width: 1200,
          height: 630,
          alt: pageTitle,
        },
      ],
      locale: 'en_US',
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: pageTitle,
      description: pageDescription,
      images: [pageImage],
      creator: SITE_CONFIG.links.twitter,
    },
    robots: {
      index: !noIndex,
      follow: !noIndex,
      googleBot: {
        index: !noIndex,
        follow: !noIndex,
        'max-video-preview': -1,
        'max-image-preview': 'large',
        'max-snippet': -1,
      },
    },
    // Add geo-location meta tags for better local SEO
    other: {
      'geo.region': 'IN',
      'geo.placename': 'Indore, Burhanpur, Khandwa, Bhopal, Dehradun, Noida, Ghaziabad, Delhi, Raver, Pune, Bangalore',
      'geo.position': '22.7196,75.8577;23.2599,77.4126;21.8256,76.0481;23.2599,77.4126;30.3165,78.0322;28.5355,77.3910;28.6692,77.4538;28.7041,77.1025;21.2584,76.0567;18.5204,73.8567;12.9716,77.5946',
      'ICBM': '22.7196,75.8577,23.2599,77.4126,21.8256,76.0481,23.2599,77.4126,30.3165,78.0322,28.5355,77.3910,28.6692,77.4538,28.7041,77.1025,21.2584,76.0567,18.5204,73.8567,12.9716,77.5946',
      'language': 'en',
      'coverage': 'Worldwide',
      'target': 'India',
      'distribution': 'Global',
      'rating': 'General',
      'revisit-after': '7 days',
      'author': 'Shivay Finance and Services',
      'publisher': 'Shivay Finance and Services',
      'category': 'Financial Services, Home Loans, Personal Loans, Business Loans',
      'service-type': 'Financial Services',
      'area-served': 'Indore, Burhanpur, Khandwa, Bhopal, Dehradun, Noida, Ghaziabad, Delhi, Raver, Pune, Bangalore',
    },
    // Add verification codes when available for Google Search Console, Bing, etc.
    // verification: {
    //   google: 'your-google-verification-code',
    //   bing: 'your-bing-verification-code',
    // },
  };
}

